export const blocks = Blockly.common.createBlockDefinitionsFromJsonArray([
  {
    type: "trigger",
    colour: 160,
    message0: "条件",
    message1: "%1",
    args1: [{ type: "input_statement", name: "CONDITIONS" }],
    message2: "效果",
    message3: "%1",
    args3: [{ type: "input_statement", name: "EFFECTS" }],
  },
  {
    type: "effect",
    colour: 160,
    message0: "效果",
    message1: "%1",
    args1: [{ type: "input_statement", name: "EFFECTS" }],
  },
  {
    type: "boolean",
    output: "Boolean",
    colour: 160,
    message0: "%1",
    args0: [
      {
        type: "field_dropdown",
        name: "BOOL",
        options: [
          ["true", "T"],
          ["false", "F"],
        ],
      },
    ],
  },
  {
    type: "number",
    output: "Number",
    colour: 160,
    message0: "%1",
    args0: [{ type: "field_number", name: "NUM" }],
  },
  {
    type: "min_coin",
    previousStatement: null,
    nextStatement: null,
    colour: 360,
    message0: "将掉落金币最小值设为 %1",
    args0: [{ type: "input_value", name: "NUM", check: "Number" }],
  },
  {
    type: "max_coin",
    previousStatement: null,
    nextStatement: null,
    colour: 360,
    message0: "将掉落金币最大值设为 %1",
    args0: [{ type: "input_value", name: "NUM", check: "Number" }],
  },
  {
    type: "act_weight",
    previousStatement: null,
    nextStatement: null,
    colour: 360,
    message0: "将己方主动权值设为 %1",
    args0: [{ type: "input_value", name: "NUM", check: "Number" }],
  },
  {
    type: "pass_weight",
    previousStatement: null,
    nextStatement: null,
    colour: 360,
    message0: "将己方被动权值设为 %1",
    args0: [{ type: "input_value", name: "NUM", check: "Number" }],
  },
  {
    type: "Aact_weight",
    previousStatement: null,
    nextStatement: null,
    colour: 360,
    message0: "将对方主动权值设为 %1",
    args0: [{ type: "input_value", name: "NUM", check: "Number" }],
  },
  {
    type: "Apass_weight",
    previousStatement: null,
    nextStatement: null,
    colour: 360,
    message0: "将对方被动权值设为 %1",
    args0: [{ type: "input_value", name: "NUM", check: "Number" }],
  },
  {
    type: "speed",
    previousStatement: null,
    nextStatement: null,
    colour: 360,
    message0: "将己方速度设为 %1",
    args0: [{ type: "input_value", name: "NUM", check: "Number" }],
  },
  {
    type: "defense",
    previousStatement: null,
    nextStatement: null,
    colour: 360,
    message0: "将己方防御设为 %1",
    args0: [{ type: "input_value", name: "NUM", check: "Number" }],
  },
  {
    type: "attact",
    previousStatement: null,
    nextStatement: null,
    colour: 360,
    message0: "将己方攻击力设为 %1",
    args0: [{ type: "input_value", name: "NUM", check: "Number" }],
  },
  {
    type: "trueAttact",
    previousStatement: null,
    nextStatement: null,
    colour: 360,
    message0: "将最终伤害值设为 %1",
    args0: [{ type: "input_value", name: "NUM", check: "Number" }],
  },
  {
    type: "fre",
    previousStatement: null,
    nextStatement: null,
    colour: 360,
    message0: "将抢劫次数上限设为 %1",
    args0: [{ type: "input_value", name: "NUM", check: "Number" }],
  },
  {
    type: "costFre",
    previousStatement: null,
    nextStatement: null,
    colour: 360,
    message0: "将本次抢劫次数消耗设置为 %1",
    args0: [{ type: "input_value", name: "NUM", check: "Number" }],
  },
  {
    type: "SeeChaMay",
    previousStatement: null,
    nextStatement: null,
    colour: 360,
    message0: "查看对方模糊权值",
  },
  {
    type: "SeeCha",
    previousStatement: null,
    nextStatement: null,
    colour: 360,
    message0: "查看对方准确权值",
  },
  {
    type: "pro_get",
    previousStatement: null,
    nextStatement: null,
    colour: 360,
    message0: "额外获得 %1 倍的金币",
    args0: [{ type: "input_value", name: "PRO", check: "Number" }],
    message1: "最少获得 %1 的金币",
    args1: [{ type: "input_value", name: "MIN", check: "Number" }],
    message2: "最多获得 %1 的金币",
    args2: [{ type: "input_value", name: "MAX", check: "Number" }],
  },
  ////////////////////////////////////////////////////////////////////////////////////////////////
  {
    type: "append",
    previousStatement: null,
    nextStatement: null,
    colour: 210,
    message0: "追加文本 %1",
    args0: [{ type: "input_value", name: "TEXT", check: "String" }],
  },
  {
    type: "append2",
    previousStatement: null,
    nextStatement: null,
    colour: 210,
    message0: "追加数字 %1",
    args0: [{ type: "input_value", name: "NUM", check: "Number" }],
  },
  {
    type: "_finish",
    previousStatement: null,
    nextStatement: null,
    colour: 210,
    message0: "结束并发送文本 %1",
    args0: [{ type: "input_value", name: "TEXT", check: "String" }],
  },
  {
    type: "slic",
    previousStatement: null,
    nextStatement: null,
    colour: 210,
    message0: "切片 [ %1 : %2 : %3 ]",
    args0: [
      { type: "input_value", name: "START", check: "Number" },
      { type: "input_value", name: "END", check: "Number" },
      { type: "input_value", name: "STEP", check: "Number" },
    ],
  },
  {
    type: "newTempNum",
    previousStatement: null,
    nextStatement: null,
    inputsInline: true,
    colour: 210,
    message0: "新建变量 %1 = %2",
    args0: [
      { type: "field_input", name: "VAR" },
      { type: "input_value", name: "NUM", check: "Number" },
    ],
  },
  {
    type: "toTempDigit",
    previousStatement: null,
    nextStatement: null,
    inputsInline: true,
    colour: 210,
    message0: "%1 = 数字 %2",
    args0: [
      { type: "field_input", name: "VAR" },
      { type: "input_value", name: "TEXT", check: "String" },
    ],
  },
]);
